# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cav.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderedMenus',
        ),
        migrations.AddField(
            model_name='menuorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cav.Order'),
        ),
    ]
