# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cav', '0002_auto_20160910_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
